#!/usr/bin/env bash

#
# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/
#

base=$(dirname $0)

groovy -classpath "${base}" "${base}/cd2mka.groovy" "$@"
