#!/usr/bin/env bash

#
# SPDX-FileCopyrightText: 2018 William Swartzendruber <wswartzendruber@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0
#

mkvmerge --disable-track-statistics-tags --output "$2" --title "$1" --chapters chapters.xml --global-tags tags.xml \
		--attachment-name Cover --attachment-mime-type image/jpeg --attach-file cover.jpg audio.flac
