#!/usr/bin/env bash

#
# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/
#

mkvmerge --disable-track-statistics-tags --output "$2" --title "$1" --chapters chapters.xml --global-tags tags.xml \
		--attachment-name Cover --attachment-mime-type image/jpeg --attach-file cover.jpg audio.flac
