#!/usr/bin/env bash

#
# SPDX-FileCopyrightText: 2018 William Swartzendruber <wswartzendruber@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0
#

mkvextract attachments "$1" 1:cover.jpg
mkvextract tracks "$1" 0:audio.flac
mkvextract tags "$1" > tags.xml
mkvextract chapters "$1" > chapters.xml
